name: 'String Summary'
description: 'Reads and summarizes a string input, truncates if too long, and writes to GitHub summary.'

inputs:
  input_path:
    description: 'The path to the input file to be summarized'
  input_string:
    description: 'The input string to be summarized'
    required: true
  type:
    description: 'The type of input to be processed'
    required: true
    default: 'string'
  max_length:
    description: 'Maximum length for the string output'
    required: false
    default: '1000000'  # 1MB limit
  summary_keyword:
    description: 'Keyword to search for in the input string for summary header'
    required: false
    default: 'Summary'

runs:
  using: "composite"
  steps:

    - name: Process and Publish String Summary
      shell: bash
      env:
        INPUT_STRING: ${{ inputs.input_string }}
        MAX_LENGTH: ${{ inputs.max_length }}
        SUMMARY_KEYWORD: ${{ inputs.summary_keyword }}
      run: summary.sh
