on:
  push:
jobs:
  string-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 10KB of Text
        id: generate_text
        run: |
          # Generate 1MB of text (10,000 characters)
          TEXT=$(head -c 10000 < /dev/urandom | tr -dc 'A-Za-z0-9')

          # Set the generated text as an output
          echo "text=$TEXT" >> $GITHUB_OUTPUT

      - name: Generate 1MB of Text
        id: generate_file
        run: |
          # Generate 1MB of text (1,000,000 characters)
          head -c 1000000 < /dev/urandom | tr -dc 'A-Za-z0-9' > generated_text.txt
          head -c 1000000 < /dev/urandom | tr -dc 'A-Za-z0-9' > generated_text.txt
          # Set the generated text as an output
          echo "file=generated_text.txt" >> $GITHUB_OUTPUT

      - name: Generate String Summary
        uses: ./.github/actions/summary
        with:
          input_string: |
            This is a long string that we want to process.
            It can be any string and the action will summarize it.
          max_length: 1000000  # 1MB limit
          summary_header: 'long string'

      - name: Generate 1MB String Summary
        uses: ./.github/actions/summary
        with:
          input_file: ${{ steps.generate_file.outputs.file }}
          max_length: 1000000  # 1MB limit
          summary_header: 'Very long string'
